### ISSUE TITLE
Create a menu page

### ISSUE THREAD

**Issue by AkhilaG28** [Mamata24/Delivary.com#19]
- [x] Create an category component for the items available in the restaurant.

- [x] Create a component for displaying individual Restaurant Details.

- [x] Create a component for Menu sidebar and displaying menu.

- [x] Create a component for order bag.

- [x] Modal for menu order

- [x] Map Box implemented in menu page

- [x] Dynamic restaurant detail implemented on store header page

- [x] Delivery Fee options activated

**Comment by Mamata24** [comment]
The menu page is ready and working perfectly.
